name: parsec-cloud
version: '0.6.0'
#version-script: git -C parts/parsec-core/src describe --tags
summary: Secure cloud framework # 79 char long summary
description: |
  Parsec is an open-source cloud-based application that allow simple yet
  cryptographically secure file hosting.
type: app

confinement: classic # classic is needed to have fuse working
icon: "../scripts/bin/parsec.png"
grade: devel # must be 'stable' to release into candidate/stable channels

apps:
  parsec:
    command: parsec
    desktop: parsec.desktop
    environment:
      BACKEND_URL: "tcp://ec2-54-229-174-79.eu-west-1.compute.amazonaws.com:6777"
      # SENTRY_URL: ""
    plugs:
      # TODO: useful given we use classic mode ?
      - home
      - network-bind
      - x11
      - unity7
      - opengl
      - wayland
      - desktop
      - desktop-legacy

parts:
  bootstrap:
    plugin: dump
    source: "../scripts/bin"

  parsec-core:
    plugin: dump
    source: https://github.com/Scille/parsec-cloud.git
    override-pull: |
      snapcraftctl pull

      git checkout v$SNAPCRAFT_PROJECT_VERSION
    override-build: |
      echo 'PYTHON VERSION: ' `python3.6 --version` `which python3.6`

      PYTHON_HOST_PATH=$SNAPCRAFT_PART_INSTALL/venv/bin/

      python3.6 -m venv $SNAPCRAFT_PART_INSTALL/venv --without-pip

      . $SNAPCRAFT_PART_INSTALL/venv/bin/activate

      curl https://bootstrap.pypa.io/get-pip.py | python3.6
      echo "PIP VERSION: " `pip --version`
      pip install .[postgresql,fuse] --process-dependency-links --target $SNAPCRAFT_PART_INSTALL/venv/lib/python3.6/site-packages

      sed -i "s#$SNAPCRAFT_PART_INSTALL#\$SNAP#g" $PYTHON_HOST_PATH/../pyvenv.cfg
      sed -i "s#$SNAPCRAFT_PART_INSTALL#\$SNAP#g" `find $PYTHON_HOST_PATH -type f`
      rm $PYTHON_HOST_PATH/python3.6
      ln -s ../../usr/bin/python3.6 $PYTHON_HOST_PATH/python3.6
    stage-packages:
      - python3.6
      - libc6
    build-packages:
      - python3.6-venv
      - python3
      - python3-virtualenv
      - python3-pip

  parsec-gui:
    plugin: nodejs
    source: https://github.com/Scille/parsec-gui.git
    node-engine: 8.11.3
    override-build: |
      git checkout v$SNAPCRAFT_PROJECT_VERSION
      npm install
      npm run electron:nix
      cp -v -r platforms/nix/parsec-gui-linux-x64/ $SNAPCRAFT_PART_INSTALL/parsec-gui
      rm ../install/lib/node_modules/parsec-gui
    stage-packages:
      - libgconf2-4
      - zlib1g  #  need version > 1.2.9 but 1.2.8 is provided by default...
      - libcanberra-gtk-module
      - libc6
      # Quick&dirty dependencies dump after atom snap...
      - libappindicator3-1
      - libasound2
      - libcurl3-gnutls
      - libgconf-2-4
      - libgtk-3-0
      - libnotify4
      - libnspr4
      - libnss3
      - libpcre3
      - libpulse0
      - libxss1
      - libxtst6
    after: [desktop-gtk3]
