name: parsec
version: '0.6.0'
#version-script: git -C parts/parsec-core/src describe --tags
summary: Secure cloud framework # 79 char long summary
description: |
  Parsec is an open-source cloud-based application that allow simple yet
  cryptographically secure file hosting.
type: app

confinement: classic # classic is needed to have fuse working
icon: "../scripts/bin/parsec.png"
grade: devel # must be 'stable' to release into candidate/stable channels

apps:
  parsec:
    command: parsec
    desktop: parsec.desktop
    environment:
      BACKEND_URL: "tcp://ec2-54-229-174-79.eu-west-1.compute.amazonaws.com:6777"
      # SENTRY_URL: ""

parts:
  bootstrap:
    plugin: dump
    source: "../scripts/bin"

  parsec-core:
    plugin: python
    python-version: python3
    requirements: requirements.txt
    source: https://github.com/Scille/parsec-cloud.git
    override-pull: |
      # ../install/usr/bin/python3 -c "import sys; raise SystemExit(0 if sys.version_info >= (3, 6) else 1)" || \
      #   ( \
      #   echo "Force default Python to version " `../install/usr/bin/python3.6 --version`; \
      #   rm ../install/usr/bin/python3; \
      #   ln -s python3.6 ../install/usr/bin/python3; \
      #   rm ../install/usr/bin/python3m; \
      #   ln -s python3.6m ../install/usr/bin/python3m; \
      #   )

      snapcraftctl pull

      git checkout v$SNAPCRAFT_PROJECT_VERSION
      #rm setup.py
      cp ../../../../scripts/setup.py .
      cp ../../../../scripts/requirements.txt .
    stage-packages:
      - libc6

  parsec-gui:
    plugin: nodejs
    source: https://github.com/Scille/parsec-gui.git
    node-engine: 8.11.3
    override-build: |
      git checkout v$SNAPCRAFT_PROJECT_VERSION
      npm install
      npm run electron:nix
      cp -v -r platforms/nix/parsec-gui-linux-x64/ $SNAPCRAFT_PART_INSTALL/parsec-gui
      rm ../install/lib/node_modules/parsec-gui
    stage-packages:
      - libgconf2-4
      - zlib1g  #  need version > 1.2.9 but 1.2.8 is provided by default...
      - libcanberra-gtk-module
      - libc6
      # Quick&dirty dependencies dump after atom snap...
      - libappindicator3-1
      - libasound2
      - libcurl3-gnutls
      - libgconf-2-4
      - libgtk-3-0
      - libnotify4
      - libnspr4
      - libnss3
      - libpcre3
      - libpulse0
      - libxss1
      - libxtst6
