name: parsec
version: '0.9.2'
#version-script: git -C parts/parsec-core/src describe --tags
summary: Secure cloud framework # 79 char long summary
description: |
  Parsec is an open-source cloud-based application that allow simple yet
  cryptographically secure file hosting.
type: app

confinement: classic # classic is needed to have fuse working
icon: "../scripts/bin/parsec.png"
grade: stable # must be 'stable' to release into candidate/stable channels

apps:
  parsec:
    command: parsec
    desktop: parsec.desktop
    environment:
      SENTRY_URL: https://863e60bbef39406896d2b7a5dbd491bb@sentry.io/1212848
  cli:
    command: parsec-cli
    desktop: parsec.desktop
    environment:
      SENTRY_URL: https://863e60bbef39406896d2b7a5dbd491bb@sentry.io/1212848

parts:
  bootstrap:
    plugin: dump
    source: "../scripts/bin"

  parsec-core:
    plugin: dump
    source: https://github.com/Scille/parsec-cloud.git
    override-pull: |
      snapcraftctl pull

      git checkout v$SNAPCRAFT_PROJECT_VERSION
    override-build: |
      echo 'PYTHON VERSION: ' `python3.6 --version` `which python3.6`

      PYTHON_HOST_PATH=$SNAPCRAFT_PART_INSTALL/venv/bin/

      python3.6 -m venv $SNAPCRAFT_PART_INSTALL/venv --without-pip

      . $SNAPCRAFT_PART_INSTALL/venv/bin/activate

      curl https://bootstrap.pypa.io/get-pip.py | python3.6
      echo "PIP VERSION: " `pip --version`
      pip install .[core] --target $SNAPCRAFT_PART_INSTALL/venv/lib/python3.6/site-packages

      sed -i "s#$SNAPCRAFT_PART_INSTALL#\$SNAP#g" $PYTHON_HOST_PATH/../pyvenv.cfg
      sed -i "s#$SNAPCRAFT_PART_INSTALL#\$SNAP#g" `find $PYTHON_HOST_PATH -type f`
      rm $PYTHON_HOST_PATH/python3.6
      ln -s ../../usr/bin/python3.6 $PYTHON_HOST_PATH/python3.6
    stage-packages:
      - python3.6
      - libc6
    build-packages:
      - curl
      - python3.6-venv
      - python3
      - python3-virtualenv
      - python3-pip
